spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: bootcamp
    password: backendpass
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
server:
  port: 8080
  servlet:
    context-path: /api
api:
  SECRETKEY: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  EXPIRATION: 3600000